"""MumPy public package exports."""

from . import _core as _core_module
from . import fallbacks, fft, linalg, random, testing
from ._version import __version__
from ._wrapping import MumPyArray, MumPyScalar, wrap_dynamic_attr_value, wrap_public_callable

_CORE_EXPORTS = (
    "ndarray",
    "newaxis",
    "bool_",
    "int8",
    "int16",
    "int32",
    "int64",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "float16",
    "float32",
    "float64",
    "bfloat16",
    "complex64",
    "pi",
    "e",
    "inf",
    "nan",
    "dtype",
    "finfo",
    "iinfo",
    "FallbackDisabledError",
    "strict_fallbacks_enabled",
    "set_strict_fallbacks",
    "array",
    "asarray",
    "asanyarray",
    "ascontiguousarray",
    "copy",
    "astype",
    "zeros",
    "ones",
    "full",
    "empty",
    "zeros_like",
    "ones_like",
    "full_like",
    "empty_like",
    "arange",
    "linspace",
    "logspace",
    "eye",
    "identity",
    "tri",
    "diag",
    "diagflat",
    "reshape",
    "transpose",
    "permute_dims",
    "swapaxes",
    "moveaxis",
    "expand_dims",
    "squeeze",
    "flatten",
    "ravel",
    "atleast_1d",
    "atleast_2d",
    "atleast_3d",
    "concatenate",
    "stack",
    "hstack",
    "vstack",
    "row_stack",
    "dstack",
    "column_stack",
    "append",
    "insert",
    "delete",
    "split",
    "array_split",
    "vsplit",
    "hsplit",
    "dsplit",
    "broadcast_to",
    "broadcast_arrays",
    "take",
    "take_along_axis",
    "repeat",
    "tile",
    "where",
    "choose",
    "select",
    "piecewise",
    "clip",
    "pad",
    "roll",
    "flip",
    "fliplr",
    "flipud",
    "rot90",
    "diagonal",
    "trace",
    "tril",
    "triu",
    "add",
    "subtract",
    "multiply",
    "divide",
    "true_divide",
    "floor_divide",
    "remainder",
    "mod",
    "power",
    "square",
    "reciprocal",
    "negative",
    "positive",
    "abs",
    "absolute",
    "sign",
    "exp",
    "expm1",
    "log",
    "log1p",
    "log2",
    "log10",
    "sqrt",
    "rsqrt",
    "sin",
    "cos",
    "tan",
    "arcsin",
    "arccos",
    "arctan",
    "sinh",
    "cosh",
    "tanh",
    "degrees",
    "radians",
    "deg2rad",
    "rad2deg",
    "floor",
    "ceil",
    "round",
    "trunc",
    "maximum",
    "minimum",
    "equal",
    "not_equal",
    "greater",
    "greater_equal",
    "less",
    "less_equal",
    "logical_and",
    "logical_or",
    "logical_xor",
    "logical_not",
    "bitwise_and",
    "bitwise_or",
    "bitwise_xor",
    "bitwise_not",
    "isnan",
    "isinf",
    "isfinite",
    "nan_to_num",
    "isclose",
    "allclose",
    "array_equal",
    "sum",
    "prod",
    "mean",
    "std",
    "var",
    "median",
    "quantile",
    "percentile",
    "nanquantile",
    "nanpercentile",
    "average",
    "cov",
    "corrcoef",
    "nansum",
    "nanprod",
    "nanmean",
    "nanstd",
    "nanvar",
    "nanmedian",
    "min",
    "max",
    "amin",
    "amax",
    "nanmin",
    "nanmax",
    "ptp",
    "argmin",
    "argmax",
    "nanargmin",
    "nanargmax",
    "all",
    "any",
    "count_nonzero",
    "nonzero",
    "flatnonzero",
    "argwhere",
    "cumsum",
    "cumprod",
    "diff",
    "ediff1d",
    "gradient",
    "trapezoid",
    "trapz",
    "sort",
    "argsort",
    "partition",
    "argpartition",
    "lexsort",
    "sort_complex",
    "searchsorted",
    "digitize",
    "bincount",
    "histogram",
    "histogram2d",
    "histogramdd",
    "interp",
    "unique",
    "in1d",
    "isin",
    "intersect1d",
    "union1d",
    "setdiff1d",
    "setxor1d",
    "compress",
    "extract",
    "dot",
    "vdot",
    "inner",
    "outer",
    "matmul",
    "tensordot",
    "einsum",
    "kron",
    "cross",
    "meshgrid",
    "indices",
    "ix_",
    "unravel_index",
    "ravel_multi_index",
    "diag_indices",
    "diag_indices_from",
    "triu_indices",
    "triu_indices_from",
    "tril_indices",
    "tril_indices_from",
    "shape",
    "ndim",
    "size",
    "item",
    "tolist",
    "isscalar",
    "conj",
    "conjugate",
    "real",
    "imag",
    "eval",
)

for _name in _CORE_EXPORTS:
    globals()[_name] = getattr(_core_module, _name)

for _name in _CORE_EXPORTS:
    _obj = globals()[_name]
    if callable(_obj) and not isinstance(_obj, type):
        globals()[_name] = wrap_public_callable(_obj, api_name=_name)

ndarray = MumPyArray

__all__ = _CORE_EXPORTS + (
    "MumPyArray",
    "MumPyScalar",
    "random",
    "linalg",
    "fft",
    "testing",
    "fallbacks",
    "__version__",
)  # pyright: ignore[reportUnsupportedDunderAll]


def __getattr__(name: str):
    if name in globals():
        return globals()[name]
    value = getattr(_core_module, name)
    value = wrap_dynamic_attr_value(name, value)
    globals()[name] = value
    return value


def __dir__():
    return sorted(__all__)
