"""Manifest of default-dtype parity audit cases and explicit API classifications."""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, Literal

import numpy as np

import mumpy as mp

ComparisonKind = Literal["numpy", "expected"]
ReturnKind = Literal["array", "scalar", "python", "infer"]
ClassificationKind = Literal[
    "tested",
    "documented-exception",
    "non-numeric-output",
    "no-default-dtype",
]


@dataclass(frozen=True)
class DtypeCase:
    """A single dtype-parity assertion case."""

    case_id: str
    surface: str
    public_name: str
    mumpy_factory: Callable[[], Any]
    numpy_factory: Callable[[], Any] | None
    comparison: ComparisonKind = "numpy"
    expected_dtype_name: str | None = None
    expected_shape: tuple[int, ...] | None = None
    expected_return_kind: ReturnKind = "infer"


def _seed_mp(seed: int) -> None:
    mp.random.seed(seed)


def _mp_rng(seed: int) -> mp.random.Generator:
    return mp.random.default_rng(seed)


def _np_rng(seed: int) -> np.random.Generator:
    return np.random.default_rng(seed)


DTYPE_CASES: tuple[DtypeCase, ...] = (
    DtypeCase("mumpy.array.int_list", "mumpy", "array", lambda: mp.array([1, 2, 3]), lambda: np.array([1, 2, 3])),
    DtypeCase(
        "mumpy.array.complex_list",
        "mumpy",
        "array",
        lambda: mp.array([1 + 2j, 3 + 4j]),
        lambda: np.array([1 + 2j, 3 + 4j]),
        comparison="expected",
        expected_dtype_name="complex64",
    ),
    DtypeCase(
        "mumpy.asarray.int_list",
        "mumpy",
        "asarray",
        lambda: mp.asarray([1, 2, 3]),
        lambda: np.asarray([1, 2, 3]),
    ),
    DtypeCase("mumpy.zeros", "mumpy", "zeros", lambda: mp.zeros((2,)), lambda: np.zeros((2,))),
    DtypeCase("mumpy.ones", "mumpy", "ones", lambda: mp.ones((2,)), lambda: np.ones((2,))),
    DtypeCase("mumpy.full.int", "mumpy", "full", lambda: mp.full((2,), 7), lambda: np.full((2,), 7)),
    DtypeCase("mumpy.empty", "mumpy", "empty", lambda: mp.empty((2,)), lambda: np.empty((2,))),
    DtypeCase("mumpy.arange.int", "mumpy", "arange", lambda: mp.arange(5), lambda: np.arange(5)),
    DtypeCase(
        "mumpy.linspace",
        "mumpy",
        "linspace",
        lambda: mp.linspace(0.0, 1.0, num=5),
        lambda: np.linspace(0.0, 1.0, num=5),
    ),
    DtypeCase(
        "mumpy.logspace",
        "mumpy",
        "logspace",
        lambda: mp.logspace(0.0, 2.0, num=4),
        lambda: np.logspace(0.0, 2.0, num=4),
    ),
    DtypeCase(
        "mumpy.geomspace",
        "mumpy",
        "geomspace",
        lambda: mp.geomspace(1.0, 16.0, num=5),
        lambda: np.geomspace(1.0, 16.0, num=5),
    ),
    DtypeCase("mumpy.eye", "mumpy", "eye", lambda: mp.eye(3), lambda: np.eye(3)),
    DtypeCase("mumpy.identity", "mumpy", "identity", lambda: mp.identity(3), lambda: np.identity(3)),
    DtypeCase("mumpy.tri", "mumpy", "tri", lambda: mp.tri(3, 4), lambda: np.tri(3, 4)),
    DtypeCase(
        "mumpy.sum.int32",
        "mumpy",
        "sum",
        lambda: mp.sum(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.sum(np.array([1, 2, 3], dtype=np.int32)),
        expected_shape=(),
    ),
    DtypeCase(
        "mumpy.mean.int32",
        "mumpy",
        "mean",
        lambda: mp.mean(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.mean(np.array([1, 2, 3], dtype=np.int32)),
        expected_shape=(),
    ),
    DtypeCase(
        "mumpy.prod.int32",
        "mumpy",
        "prod",
        lambda: mp.prod(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.prod(np.array([1, 2, 3], dtype=np.int32)),
        expected_shape=(),
    ),
    DtypeCase(
        "mumpy.var.int32",
        "mumpy",
        "var",
        lambda: mp.var(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.var(np.array([1, 2, 3], dtype=np.int32)),
        expected_shape=(),
    ),
    DtypeCase(
        "mumpy.std.int32",
        "mumpy",
        "std",
        lambda: mp.std(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.std(np.array([1, 2, 3], dtype=np.int32)),
        expected_shape=(),
    ),
    DtypeCase(
        "mumpy.nansum.int32",
        "mumpy",
        "nansum",
        lambda: mp.nansum(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.nansum(np.array([1, 2, 3], dtype=np.int32)),
        expected_shape=(),
    ),
    DtypeCase(
        "mumpy.nanprod.int32",
        "mumpy",
        "nanprod",
        lambda: mp.nanprod(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.nanprod(np.array([1, 2, 3], dtype=np.int32)),
        expected_shape=(),
    ),
    DtypeCase(
        "mumpy.nanmean.float32",
        "mumpy",
        "nanmean",
        lambda: mp.nanmean(mp.array([1.0, np.nan, 3.0], dtype=mp.float32)),
        lambda: np.nanmean(np.array([1.0, np.nan, 3.0], dtype=np.float32)),
        expected_return_kind="scalar",
    ),
    DtypeCase(
        "mumpy.nanvar.float32",
        "mumpy",
        "nanvar",
        lambda: mp.nanvar(mp.array([1.0, np.nan, 3.0], dtype=mp.float32)),
        lambda: np.nanvar(np.array([1.0, np.nan, 3.0], dtype=np.float32)),
        expected_return_kind="array",
    ),
    DtypeCase(
        "mumpy.nanstd.float32",
        "mumpy",
        "nanstd",
        lambda: mp.nanstd(mp.array([1.0, np.nan, 3.0], dtype=mp.float32)),
        lambda: np.nanstd(np.array([1.0, np.nan, 3.0], dtype=np.float32)),
        expected_return_kind="array",
    ),
    DtypeCase(
        "mumpy.average.int32",
        "mumpy",
        "average",
        lambda: mp.average(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.average(np.array([1, 2, 3], dtype=np.int32)),
        expected_shape=(),
    ),
    DtypeCase(
        "mumpy.nancumsum.int32",
        "mumpy",
        "nancumsum",
        lambda: mp.nancumsum(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.nancumsum(np.array([1, 2, 3], dtype=np.int32)),
    ),
    DtypeCase(
        "mumpy.nancumprod.int32",
        "mumpy",
        "nancumprod",
        lambda: mp.nancumprod(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.nancumprod(np.array([1, 2, 3], dtype=np.int32)),
    ),
    DtypeCase(
        "mumpy.cumsum.int32",
        "mumpy",
        "cumsum",
        lambda: mp.cumsum(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.cumsum(np.array([1, 2, 3], dtype=np.int32)),
    ),
    DtypeCase(
        "mumpy.cumprod.int32",
        "mumpy",
        "cumprod",
        lambda: mp.cumprod(mp.array([1, 2, 3], dtype=mp.int32)),
        lambda: np.cumprod(np.array([1, 2, 3], dtype=np.int32)),
    ),
    DtypeCase(
        "mumpy.trace.int32",
        "mumpy",
        "trace",
        lambda: mp.trace(mp.array([[1, 2], [3, 4]], dtype=mp.int32)),
        lambda: np.trace(np.array([[1, 2], [3, 4]], dtype=np.int32)),
        expected_shape=(),
    ),
    DtypeCase(
        "mumpy.float_power",
        "mumpy",
        "float_power",
        lambda: mp.float_power(2, 3),
        lambda: np.float_power(2, 3),
        expected_shape=(),
    ),
    DtypeCase(
        "mumpy.histogram.edges.int",
        "mumpy",
        "histogram",
        lambda: mp.histogram(mp.array([1, 2, 3], dtype=mp.int32), bins=3)[1],
        lambda: np.histogram(np.array([1, 2, 3], dtype=np.int32), bins=3)[1],
    ),
    DtypeCase(
        "mumpy.searchsorted",
        "mumpy",
        "searchsorted",
        lambda: mp.searchsorted(mp.array([1, 3, 5], dtype=mp.int32), [0, 4, 7]),
        lambda: np.searchsorted(np.array([1, 3, 5], dtype=np.int32), [0, 4, 7]),
    ),
    DtypeCase(
        "mumpy.digitize",
        "mumpy",
        "digitize",
        lambda: mp.digitize([0.5, 1.5], [0.0, 1.0, 2.0]),
        lambda: np.digitize([0.5, 1.5], [0.0, 1.0, 2.0]),
    ),
    DtypeCase(
        "mumpy.flatnonzero",
        "mumpy",
        "flatnonzero",
        lambda: mp.flatnonzero(mp.array([[0, 1], [2, 0]], dtype=mp.int32)),
        lambda: np.flatnonzero(np.array([[0, 1], [2, 0]], dtype=np.int32)),
    ),
    DtypeCase(
        "mumpy.argwhere",
        "mumpy",
        "argwhere",
        lambda: mp.argwhere(mp.array([[0, 1], [2, 0]], dtype=mp.int32)),
        lambda: np.argwhere(np.array([[0, 1], [2, 0]], dtype=np.int32)),
    ),
    DtypeCase(
        "mumpy.ravel_multi_index",
        "mumpy",
        "ravel_multi_index",
        lambda: mp.ravel_multi_index(([1, 0], [0, 2]), (2, 3)),
        lambda: np.ravel_multi_index(([1, 0], [0, 2]), (2, 3)),
    ),
    DtypeCase(
        "mumpy.linalg.lstsq.residuals.empty",
        "mumpy.linalg",
        "lstsq",
        lambda: mp.linalg.lstsq(np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float64), np.array([1.0, 2.0]))[1],
        lambda: np.linalg.lstsq(np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float64), np.array([1.0, 2.0]), rcond=None)[
            1
        ],
    ),
    DtypeCase(
        "mumpy.fft.fftfreq",
        "mumpy.fft",
        "fftfreq",
        lambda: mp.fft.fftfreq(8, d=0.5),
        lambda: np.fft.fftfreq(8, d=0.5),
    ),
    DtypeCase(
        "mumpy.fft.rfftfreq",
        "mumpy.fft",
        "rfftfreq",
        lambda: mp.fft.rfftfreq(9, d=0.25),
        lambda: np.fft.rfftfreq(9, d=0.25),
    ),
    DtypeCase(
        "mumpy.random.random",
        "mumpy.random",
        "random",
        lambda: (_seed_mp(11), mp.random.random(4))[1],
        lambda: _np_rng(11).random(4),
    ),
    DtypeCase(
        "mumpy.random.randn",
        "mumpy.random",
        "randn",
        lambda: (_seed_mp(12), mp.random.randn(4))[1],
        lambda: _np_rng(12).standard_normal(4),
    ),
    DtypeCase(
        "mumpy.random.randint",
        "mumpy.random",
        "randint",
        lambda: (_seed_mp(13), mp.random.randint(10, size=4))[1],
        lambda: _np_rng(13).integers(10, size=4),
    ),
    DtypeCase(
        "mumpy.random.poisson",
        "mumpy.random",
        "poisson",
        lambda: (_seed_mp(14), mp.random.poisson(3.0, size=4))[1],
        lambda: _np_rng(14).poisson(3.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.choice.int_population",
        "mumpy.random",
        "choice",
        lambda: (_seed_mp(15), mp.random.choice(5, size=4))[1],
        lambda: _np_rng(15).choice(5, size=4),
    ),
    DtypeCase(
        "mumpy.random.permutation.int_population",
        "mumpy.random",
        "permutation",
        lambda: (_seed_mp(16), mp.random.permutation(5))[1],
        lambda: _np_rng(16).permutation(5),
    ),
    DtypeCase(
        "mumpy.random.truncated_normal",
        "mumpy.random",
        "truncated_normal",
        lambda: (_seed_mp(17), mp.random.truncated_normal(-1.0, 1.0, size=4))[1],
        None,
        comparison="expected",
        expected_dtype_name="float64",
    ),
    DtypeCase(
        "mumpy.random.multivariate_normal",
        "mumpy.random",
        "multivariate_normal",
        lambda: (_seed_mp(18), mp.random.multivariate_normal([0.0, 0.0], [[1.0, 0.0], [0.0, 1.0]], size=2))[1],
        lambda: _np_rng(18).multivariate_normal([0.0, 0.0], [[1.0, 0.0], [0.0, 1.0]], size=2),
    ),
    DtypeCase(
        "mumpy.random.random_sample",
        "mumpy.random",
        "random_sample",
        lambda: (_seed_mp(31), mp.random.random_sample(4))[1],
        lambda: _np_rng(31).random(4),
    ),
    DtypeCase(
        "mumpy.random.sample",
        "mumpy.random",
        "sample",
        lambda: (_seed_mp(32), mp.random.sample(4))[1],
        lambda: _np_rng(32).random(4),
    ),
    DtypeCase(
        "mumpy.random.ranf",
        "mumpy.random",
        "ranf",
        lambda: (_seed_mp(33), mp.random.ranf(4))[1],
        lambda: _np_rng(33).random(4),
    ),
    DtypeCase(
        "mumpy.random.rand",
        "mumpy.random",
        "rand",
        lambda: (_seed_mp(34), mp.random.rand(4))[1],
        lambda: _np_rng(34).random(4),
    ),
    DtypeCase(
        "mumpy.random.uniform",
        "mumpy.random",
        "uniform",
        lambda: (_seed_mp(35), mp.random.uniform(size=4))[1],
        lambda: _np_rng(35).uniform(size=4),
    ),
    DtypeCase(
        "mumpy.random.normal",
        "mumpy.random",
        "normal",
        lambda: (_seed_mp(36), mp.random.normal(size=4))[1],
        lambda: _np_rng(36).normal(size=4),
    ),
    DtypeCase(
        "mumpy.random.standard_normal",
        "mumpy.random",
        "standard_normal",
        lambda: (_seed_mp(37), mp.random.standard_normal(4))[1],
        lambda: _np_rng(37).standard_normal(4),
    ),
    DtypeCase(
        "mumpy.random.laplace",
        "mumpy.random",
        "laplace",
        lambda: (_seed_mp(38), mp.random.laplace(size=4))[1],
        lambda: _np_rng(38).laplace(size=4),
    ),
    DtypeCase(
        "mumpy.random.gumbel",
        "mumpy.random",
        "gumbel",
        lambda: (_seed_mp(39), mp.random.gumbel(size=4))[1],
        lambda: _np_rng(39).gumbel(size=4),
    ),
    DtypeCase(
        "mumpy.random.exponential",
        "mumpy.random",
        "exponential",
        lambda: (_seed_mp(40), mp.random.exponential(size=4))[1],
        lambda: _np_rng(40).exponential(size=4),
    ),
    DtypeCase(
        "mumpy.random.standard_gamma",
        "mumpy.random",
        "standard_gamma",
        lambda: (_seed_mp(41), mp.random.standard_gamma(2.0, size=4))[1],
        lambda: _np_rng(41).standard_gamma(2.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.gamma",
        "mumpy.random",
        "gamma",
        lambda: (_seed_mp(42), mp.random.gamma(2.0, size=4))[1],
        lambda: _np_rng(42).gamma(2.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.chisquare",
        "mumpy.random",
        "chisquare",
        lambda: (_seed_mp(43), mp.random.chisquare(4.0, size=4))[1],
        lambda: _np_rng(43).chisquare(4.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.f",
        "mumpy.random",
        "f",
        lambda: (_seed_mp(44), mp.random.f(5.0, 7.0, size=4))[1],
        lambda: _np_rng(44).f(5.0, 7.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.beta",
        "mumpy.random",
        "beta",
        lambda: (_seed_mp(45), mp.random.beta(2.0, 5.0, size=4))[1],
        lambda: _np_rng(45).beta(2.0, 5.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.dirichlet",
        "mumpy.random",
        "dirichlet",
        lambda: (_seed_mp(46), mp.random.dirichlet([1.0, 2.0, 3.0], size=3))[1],
        lambda: _np_rng(46).dirichlet([1.0, 2.0, 3.0], size=3),
    ),
    DtypeCase(
        "mumpy.random.standard_t",
        "mumpy.random",
        "standard_t",
        lambda: (_seed_mp(47), mp.random.standard_t(5.0, size=4))[1],
        lambda: _np_rng(47).standard_t(5.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.multinomial",
        "mumpy.random",
        "multinomial",
        lambda: (_seed_mp(48), mp.random.multinomial(5, [0.2, 0.3, 0.5], size=3))[1],
        lambda: _np_rng(48).multinomial(5, [0.2, 0.3, 0.5], size=3),
    ),
    DtypeCase(
        "mumpy.random.negative_binomial",
        "mumpy.random",
        "negative_binomial",
        lambda: (_seed_mp(49), mp.random.negative_binomial(4.0, 0.35, size=4))[1],
        lambda: _np_rng(49).negative_binomial(4.0, 0.35, size=4),
    ),
    DtypeCase(
        "mumpy.random.binomial",
        "mumpy.random",
        "binomial",
        lambda: (_seed_mp(50), mp.random.binomial(10, 0.3, size=4))[1],
        lambda: _np_rng(50).binomial(10, 0.3, size=4),
    ),
    DtypeCase(
        "mumpy.random.integers",
        "mumpy.random",
        "integers",
        lambda: (_seed_mp(51), mp.random.integers(10, size=4))[1],
        lambda: _np_rng(51).integers(10, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.random",
        "mumpy.random.Generator",
        "random",
        lambda: _mp_rng(21).random(4),
        lambda: _np_rng(21).random(4),
    ),
    DtypeCase(
        "mumpy.random.Generator.standard_normal",
        "mumpy.random.Generator",
        "standard_normal",
        lambda: _mp_rng(22).standard_normal(4),
        lambda: _np_rng(22).standard_normal(4),
    ),
    DtypeCase(
        "mumpy.random.Generator.random_sample",
        "mumpy.random.Generator",
        "random_sample",
        lambda: _mp_rng(61).random_sample(4),
        lambda: _np_rng(61).random(4),
    ),
    DtypeCase(
        "mumpy.random.Generator.uniform",
        "mumpy.random.Generator",
        "uniform",
        lambda: _mp_rng(62).uniform(size=4),
        lambda: _np_rng(62).uniform(size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.normal",
        "mumpy.random.Generator",
        "normal",
        lambda: _mp_rng(63).normal(size=4),
        lambda: _np_rng(63).normal(size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.laplace",
        "mumpy.random.Generator",
        "laplace",
        lambda: _mp_rng(64).laplace(size=4),
        lambda: _np_rng(64).laplace(size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.gumbel",
        "mumpy.random.Generator",
        "gumbel",
        lambda: _mp_rng(65).gumbel(size=4),
        lambda: _np_rng(65).gumbel(size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.exponential",
        "mumpy.random.Generator",
        "exponential",
        lambda: _mp_rng(66).exponential(size=4),
        lambda: _np_rng(66).exponential(size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.standard_exponential",
        "mumpy.random.Generator",
        "standard_exponential",
        lambda: _mp_rng(67).standard_exponential(4),
        lambda: _np_rng(67).standard_exponential(4),
    ),
    DtypeCase(
        "mumpy.random.Generator.rayleigh",
        "mumpy.random.Generator",
        "rayleigh",
        lambda: _mp_rng(68).rayleigh(size=4),
        lambda: _np_rng(68).rayleigh(size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.logistic",
        "mumpy.random.Generator",
        "logistic",
        lambda: _mp_rng(69).logistic(size=4),
        lambda: _np_rng(69).logistic(size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.lognormal",
        "mumpy.random.Generator",
        "lognormal",
        lambda: _mp_rng(70).lognormal(size=4),
        lambda: _np_rng(70).lognormal(size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.standard_cauchy",
        "mumpy.random.Generator",
        "standard_cauchy",
        lambda: _mp_rng(71).standard_cauchy(4),
        lambda: _np_rng(71).standard_cauchy(4),
    ),
    DtypeCase(
        "mumpy.random.Generator.triangular",
        "mumpy.random.Generator",
        "triangular",
        lambda: _mp_rng(72).triangular(0.0, 0.5, 1.0, size=4),
        lambda: _np_rng(72).triangular(0.0, 0.5, 1.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.geometric",
        "mumpy.random.Generator",
        "geometric",
        lambda: _mp_rng(72).geometric(0.5, size=4),
        lambda: _np_rng(72).geometric(0.5, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.weibull",
        "mumpy.random.Generator",
        "weibull",
        lambda: _mp_rng(73).weibull(1.5, size=4),
        lambda: _np_rng(73).weibull(1.5, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.power",
        "mumpy.random.Generator",
        "power",
        lambda: _mp_rng(74).power(2.0, size=4),
        lambda: _np_rng(74).power(2.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.pareto",
        "mumpy.random.Generator",
        "pareto",
        lambda: _mp_rng(75).pareto(2.0, size=4),
        lambda: _np_rng(75).pareto(2.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.standard_gamma",
        "mumpy.random.Generator",
        "standard_gamma",
        lambda: _mp_rng(76).standard_gamma(2.0, size=4),
        lambda: _np_rng(76).standard_gamma(2.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.gamma",
        "mumpy.random.Generator",
        "gamma",
        lambda: _mp_rng(77).gamma(2.0, size=4),
        lambda: _np_rng(77).gamma(2.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.chisquare",
        "mumpy.random.Generator",
        "chisquare",
        lambda: _mp_rng(78).chisquare(4.0, size=4),
        lambda: _np_rng(78).chisquare(4.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.f",
        "mumpy.random.Generator",
        "f",
        lambda: _mp_rng(79).f(5.0, 7.0, size=4),
        lambda: _np_rng(79).f(5.0, 7.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.beta",
        "mumpy.random.Generator",
        "beta",
        lambda: _mp_rng(80).beta(2.0, 5.0, size=4),
        lambda: _np_rng(80).beta(2.0, 5.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.dirichlet",
        "mumpy.random.Generator",
        "dirichlet",
        lambda: _mp_rng(81).dirichlet([1.0, 2.0, 3.0], size=3),
        lambda: _np_rng(81).dirichlet([1.0, 2.0, 3.0], size=3),
    ),
    DtypeCase(
        "mumpy.random.Generator.standard_t",
        "mumpy.random.Generator",
        "standard_t",
        lambda: _mp_rng(82).standard_t(5.0, size=4),
        lambda: _np_rng(82).standard_t(5.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.multinomial",
        "mumpy.random.Generator",
        "multinomial",
        lambda: _mp_rng(83).multinomial(5, [0.2, 0.3, 0.5], size=3),
        lambda: _np_rng(83).multinomial(5, [0.2, 0.3, 0.5], size=3),
    ),
    DtypeCase(
        "mumpy.random.Generator.negative_binomial",
        "mumpy.random.Generator",
        "negative_binomial",
        lambda: _mp_rng(84).negative_binomial(4.0, 0.35, size=4),
        lambda: _np_rng(84).negative_binomial(4.0, 0.35, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.binomial",
        "mumpy.random.Generator",
        "binomial",
        lambda: _mp_rng(85).binomial(10, 0.3, size=4),
        lambda: _np_rng(85).binomial(10, 0.3, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.integers",
        "mumpy.random.Generator",
        "integers",
        lambda: _mp_rng(23).integers(10, size=4),
        lambda: _np_rng(23).integers(10, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.poisson",
        "mumpy.random.Generator",
        "poisson",
        lambda: _mp_rng(24).poisson(3.0, size=4),
        lambda: _np_rng(24).poisson(3.0, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.choice.int_population",
        "mumpy.random.Generator",
        "choice",
        lambda: _mp_rng(25).choice(5, size=4),
        lambda: _np_rng(25).choice(5, size=4),
    ),
    DtypeCase(
        "mumpy.random.Generator.permutation.int_population",
        "mumpy.random.Generator",
        "permutation",
        lambda: _mp_rng(26).permutation(5),
        lambda: _np_rng(26).permutation(5),
    ),
    DtypeCase(
        "mumpy.random.Generator.truncated_normal",
        "mumpy.random.Generator",
        "truncated_normal",
        lambda: _mp_rng(27).truncated_normal(-1.0, 1.0, size=4),
        None,
        comparison="expected",
        expected_dtype_name="float64",
    ),
    DtypeCase(
        "mumpy.random.Generator.multivariate_normal",
        "mumpy.random.Generator",
        "multivariate_normal",
        lambda: _mp_rng(28).multivariate_normal([0.0, 0.0], [[1.0, 0.0], [0.0, 1.0]], size=2),
        lambda: _np_rng(28).multivariate_normal([0.0, 0.0], [[1.0, 0.0], [0.0, 1.0]], size=2),
    ),
)

CASE_NAMES_BY_SURFACE: dict[str, set[str]] = {}
for _case in DTYPE_CASES:
    CASE_NAMES_BY_SURFACE.setdefault(_case.surface, set()).add(_case.public_name)

DTYPE_RELEVANT_EXPLICIT_NAMES_BY_SURFACE: dict[str, set[str]] = {
    "mumpy": {
        "array",
        "asarray",
        "zeros",
        "ones",
        "full",
        "empty",
        "arange",
        "linspace",
        "logspace",
        "geomspace",
        "eye",
        "identity",
        "tri",
        "sum",
        "prod",
        "mean",
        "var",
        "std",
        "nansum",
        "nanprod",
        "nanmean",
        "nanvar",
        "nanstd",
        "average",
        "cumsum",
        "cumprod",
        "nancumsum",
        "nancumprod",
        "trace",
        "float_power",
        "histogram",
        "searchsorted",
        "digitize",
        "flatnonzero",
        "argwhere",
        "ravel_multi_index",
    },
    "mumpy.linalg": {"lstsq"},
    "mumpy.fft": {"fftfreq", "rfftfreq"},
    "mumpy.random": {
        "random",
        "random_sample",
        "sample",
        "ranf",
        "rand",
        "randn",
        "uniform",
        "normal",
        "standard_normal",
        "laplace",
        "gumbel",
        "exponential",
        "randint",
        "integers",
        "standard_gamma",
        "gamma",
        "chisquare",
        "f",
        "beta",
        "dirichlet",
        "standard_t",
        "multinomial",
        "negative_binomial",
        "poisson",
        "binomial",
        "truncated_normal",
        "multivariate_normal",
        "choice",
        "permutation",
    },
    "mumpy.random.Generator": {
        "random",
        "random_sample",
        "uniform",
        "normal",
        "standard_normal",
        "integers",
        "choice",
        "permutation",
        "laplace",
        "gumbel",
        "exponential",
        "standard_exponential",
        "rayleigh",
        "logistic",
        "lognormal",
        "standard_cauchy",
        "triangular",
        "weibull",
        "power",
        "pareto",
        "geometric",
        "standard_gamma",
        "gamma",
        "chisquare",
        "f",
        "beta",
        "dirichlet",
        "standard_t",
        "multinomial",
        "negative_binomial",
        "poisson",
        "binomial",
        "truncated_normal",
        "multivariate_normal",
    },
}

DOCUMENTED_EXCEPTION_NAMES_BY_SURFACE: dict[str, set[str]] = {
    "mumpy": {"array"},
}

NON_NUMERIC_OUTPUT_NAMES_BY_SURFACE: dict[str, set[str]] = {
    "mumpy.linalg": set(),
    "mumpy.fft": set(),
    "mumpy.random": {"bytes", "seed", "split", "key"},
    "mumpy.random.Generator": {"bytes", "spawn", "bit_generator"},
}


def classify_explicit_name(surface: str, name: str) -> ClassificationKind:
    """Classify an explicit callable for default-dtype audit accounting."""
    if name in CASE_NAMES_BY_SURFACE.get(surface, set()):
        return "tested"
    if name in DOCUMENTED_EXCEPTION_NAMES_BY_SURFACE.get(surface, set()):
        return "documented-exception"
    if name in NON_NUMERIC_OUTPUT_NAMES_BY_SURFACE.get(surface, set()):
        return "non-numeric-output"
    return "no-default-dtype"
